name = "LuxCat"
uuid = "1adf876c-ebf6-4c25-9529-59df72e3cef9"
authors = ["Jacob Zelko <jacobszelko@gmail.com>"]
version = "0.0.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
FreeTypeAbstraction = "663a7486-cb36-511b-a19d-713bb74d65c9"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Luxor = "ae8d54c2-7ccd-5906-9d76-62fc9837b5bc"
MathTeXEngine = "0a4f8689-d25c-4efe-a92b-7142dfc1aa53"

[compat]
LaTeXStrings = "1"
julia = "1.6"
